/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class interfaceAdmin extends javax.swing.JFrame {

      Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public interfaceAdmin() {
        initComponents();
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("num");
        model.addColumn("depart");
        model.addColumn("arrive");
        model.addColumn("heure_D");
        model.addColumn("heure_A");
        model.addColumn("prix");
    
         String requetetrain="select*from train1";
         try{
             Class.forName("oracle.jdbc.OracleDriver");
         con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",
                 "system","souad1");
            pst=con.prepareStatement(requetetrain);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            model.addRow(new Object[]{rs.getString("num"),rs.getString("depart")
                    ,rs.getString("arrive"),rs.getString("heure_D"),
                    rs.getString("heure_A"),rs.getString("prix")});
           }
            jTable1.setModel(model);
       
             
         } catch (ClassNotFoundException | SQLException ex) {
              Logger.getLogger(interfaceAdmin.class.getName())
                      .log(Level.SEVERE, null, ex);
          }
   
    }
     interfaceAdmin(String un) {
        initComponents();
        jLabel9.setText(un);
        //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        time_a = new javax.swing.JTextField();
        time_d = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        depar = new javax.swing.JTextField();
        arriv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/user.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Ajouter ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Modifier ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("<<");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 4, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("N° vol");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 19, 85, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Gare_Destination");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 108, 129, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gare_Depart");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 72, 107, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Heure_Depart");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 32, 111, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Prix");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 107, 111, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Heure_Arrive");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 72, 111, 29));
        jPanel2.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 190, 34));
        jPanel2.add(time_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 61, 180, 31));
        jPanel2.add(time_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 21, 180, 29));

        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });
        jPanel2.add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 107, 180, 33));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°vol", "G_depart", "G_arrive", "heure_D", "heure_A", "prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 717, 210));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 159, 880, 10));
        jPanel2.add(depar, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 61, 190, 34));
        jPanel2.add(arriv, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 107, 190, 34));

        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 440));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  try{
           
      Class.forName("oracle.jdbc.OracleDriver");
      con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",
              "system","souad1");
      String sql= "UPDATE  train1 SET depart='"+depar.getText() +"',arrive='"
              +arriv.getText()+"',heure_D='"+time_d.getText()+"',heure_A='"+
              time_a.getText()+"' ,prix='"+prix.getText()+"' WHERE num='"+
              num.getText()+"'";
            pst = con.prepareStatement(sql);
          
               pst.executeUpdate();
            JOptionPane.showMessageDialog(null," update succeful");
              con.close();
            num.setText("");
            depar.setText("");
            arriv.setText("");
            time_d.setText("");
            time_a.setText("");
            prix.setText("");
            jButton2.setEnabled(true);
            
            jButton2.setEnabled(true);
        } catch (SQLException ex) {
            System.out.println("error update "+ ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(interfaceAdmin.class.getName()).log(Level.SEVERE, 
                null, ex);
    }
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("num");
        model.addColumn("depart");
        model.addColumn("arrive");
        model.addColumn("heure_D");
        model.addColumn("heure_A");
        model.addColumn("prix");
    
         String requetetrain="select*from train1";
         try{
          Class.forName("oracle.jdbc.OracleDriver");
          con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe"
                  ,"system","souad1");
            pst=con.prepareStatement(requetetrain);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
           model.addRow(new Object[] {rs.getString("num"),rs.getString("depart")
          ,rs.getString("arrive"),rs.getString("heure_D"),rs.getString("heure_A")
          ,rs.getString("prix")});
           }
            jTable1.setModel(model);
       
             
         } catch (ClassNotFoundException | SQLException ex) {
              Logger.getLogger(interfaceAdmin.class.getName()).log(Level.SEVERE
                      , null, ex);
          }
    
        
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       interfaceAdmin.super.dispose();
      interface_Voyageur  l =new interface_Voyageur ();
        l.setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           String id=num.getText();
          String depart=depar.getText();
          String arrive=arriv.getText();
          String h_dep=time_d.getText();
          String h_arr=time_a.getText();
          String pr=prix.getText(); 
        
        try {
        Class.forName("oracle.jdbc.OracleDriver");
        con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",
                "system","souad1");
       pst = con.prepareStatement("insert into train1 values (?,?,?,?,?,?)");
        pst.setString(1, id);
        pst.setString(2,depart);
        pst.setString(3,arrive);
        pst.setString(4,h_dep);      
        pst.setString(5,h_arr);
        pst.setString(6,pr);  
        pst .executeQuery();
        
       
     JOptionPane.showMessageDialog(null,"train enregistrer!!");
             num.setText("");
            depar.setText("");
            arriv.setText("");
            time_d.setText("");
            time_a.setText("");
            prix.setText("");
            con.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(interfaceAdmin .class.getName()).log(Level.SEVERE,
                    null, ex);
        }
             DefaultTableModel model=new DefaultTableModel();
        model.addColumn("num");
         model.addColumn("depart");
          model.addColumn("arrive");
        model.addColumn("heure_D");
        model.addColumn("heure_A");
         model.addColumn("prix");
         String requetetrain="select*from train1";
         try{
        Class.forName("oracle.jdbc.OracleDriver");
         con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",
                 "system","souad1");
            pst=con.prepareStatement(requetetrain);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            model.addRow(new Object[] {rs.getString("num"),rs.getString("depart")
           ,rs.getString("arrive"),rs.getString("heure_D"),rs.getString("heure_A")
                    ,rs.getString("prix")});
            }
            jTable1.setModel(model);
         } catch (ClassNotFoundException | SQLException ex) {
              Logger.getLogger(interfaceAdmin.class.getName()).log(Level.SEVERE
                      , null, ex);
          }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 //  JOptionPane.showInternalConfirmDialog(null," est ce que tu es sure que tu veux supprimer ");
        try{
      Class.forName("oracle.jdbc.OracleDriver");
        con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",
                "system","souad1");
        String sql= "delete  from TRAIN1 where num=?";
        pst = con.prepareStatement(sql);
        pst.setString(1,num.getText());
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null," bien supprimer");
             num.setText("");
            depar.setText("");
             arriv.setText("");
            time_d.setText(""); 
            time_a.setText("");
             prix.setText("");
             jButton2.setEnabled(true);
             con.close();
        } catch (SQLException ex) {
            System.out.println("error  "+ ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(interfaceAdmin.class.getName()).log(Level.SEVERE, 
           null, ex);
    }
    
   DefaultTableModel model=new DefaultTableModel();
        model.addColumn("num");
         model.addColumn("depart");
          model.addColumn("arrive");
        model.addColumn("heure_D");
        model.addColumn("heure_A");
         model.addColumn("prix");
    
         String requetetrain="select*from train1";
         try{
             Class.forName("oracle.jdbc.OracleDriver");
        con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",
                "system","souad1");
            pst=con.prepareStatement(requetetrain);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
       model.addRow(new Object[] {rs.getString("num"),rs.getString("depart"),
        rs.getString("arrive"),rs.getString("heure_D"),rs.getString("heure_A"),
        rs.getString("prix")});
           }
            jTable1.setModel(model);
       
             
         } catch (ClassNotFoundException | SQLException ex) {
              Logger.getLogger(interfaceAdmin.class.getName()).log(Level.SEVERE
                      , null, ex);
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
             DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
           int selectIndex=jTable1.getSelectedRow();
         num.setText(df.getValueAt(selectIndex,0).toString());
          depar.setText(df.getValueAt(selectIndex,1).toString());
          arriv.setText(df.getValueAt(selectIndex,2).toString());
         time_d.setText(df.getValueAt(selectIndex,3).toString());
         time_a.setText(df.getValueAt(selectIndex,4).toString()); 
         prix.setText(df.getValueAt(selectIndex,5).toString());
         jButton2.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arriv;
    private javax.swing.JTextField depar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField num;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField time_a;
    private javax.swing.JTextField time_d;
    // End of variables declaration//GEN-END:variables
}
